### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rtkramer** [inVoltag/figma-ui-color-palette#1]
Plugin is not working for me, I just get an empty frame with an empty autolayout

https://user-images.githubusercontent.com/15931910/160049649-7ff6ddec-5b07-458f-a936-e39debcfde48.mov

**Comment by inVoltag** [comment]
Hello @rtkramer,
I need to know where you're using Figma. Do you use it on your native browser or or the desktop application?

**Comment by inVoltag** [comment]
I got my answer. I fixed the bug on creating a color palette on native browsers. Could you check on this and make a feedback?
