### ISSUE TITLE
[Wrong variables values]

### ISSUE THREAD

**Issue by jomagheredia** [inVoltag/figma-ui-color-palette#118]
**Describe the bug**
Wrong variables outcome when creating a new source color producing just FFFFFF values. Already have other colors with no problem before creating a new one.

**To Reproduce**
1. Create a new source color
2. Manage local variables
3. Sync with the local variables

**Expected behavior**
Correct color shades instead of FFFFFF values

**Screenshots**
![Screenshot 2024-01-05 at 9 03 11 AM](https://github.com/inVoltag/figma-ui-color-palette/assets/5198607/c04c3c42-da8e-4e17-983b-ebc596d38e40)

**Useful information (please complete the following information):**
https://www.figma.com/file/oIbQWvAvsIux3Ff2MWx4B9/Firstoken?type=design&node-id=0%3A1&mode=design&t=7LJOBY5SONZBeZ7F-1

**Comment by inVoltag** [comment]
Hello @jomagheredia,
Thanks for your reporting. I have reproduced this bug and plan to fix it for the next version.

**Comment by inVoltag** [comment]
Hello @jomagheredia,
Feel free to test this fixed version before I release it.
Here are some quick steps to test:
- Download the Figma Desktop App.
- Download the plugin: https://github.com/inVoltag/figma-ui-color-palette/actions/runs/7506982820.
- Follow this guide to use it on Figma: https://github.com/inVoltag/figma-ui-color-palette?tab=readme-ov-file#beta-test (steps 3 and 4)

**Comment by inVoltag** [comment]
The fix has been released in the new official version. Let me know if it resolves your issue.
