### ISSUE TITLE
Realtime colors updating is not working

### ISSUE THREAD

**Issue by alex-prime-one** [inVoltag/figma-ui-color-palette#2]
MacOS, desktop app.

[Screencast](https://video.wixstatic.com/video/ee11f0_36b3564af8d84f798f5626a0e0c257d5/1080p/mp4/file.mp4)

**Comment by inVoltag** [comment]
I see there's something wrong with the real time edit. I'm going to fix the issue quickly.

**Comment by inVoltag** [comment]
I improved a bit the real-time edit responsiveness. Could you tell me if the result is acceptable? I need more investigations on improving performances.

**Comment by alex-prime-one** [comment]
Tested it. I can confirm it is way better now, but sometimes still have issues with real-time updating. But technically it is usable and working just fine.
Can you provide some info on my another request? For additional lightness. Are you going to implement it?
________________________________

**Comment by inVoltag** [comment]
Understood, I keep this performance issue in mind.
Concerning your request, could you open another issue? I'm working on it.
