### ISSUE TITLE
Inconsistent lightness

### ISSUE THREAD

**Issue by MrFussyfont** [inVoltag/figma-ui-color-palette#46]
My main interest in this plugin is to generate a palette with consistent perceived lightness and therefore consistent contrast ratios regardless of hue. However, some generated colours are darker than others, which was unexpected:

<img width="805" alt="image" src="https://user-images.githubusercontent.com/474540/225401685-bd006a24-3ace-4c27-960c-d6336128537a.png">

Using the Sim Daltonism app to view as monochrome, you can see that the greens are darker than the other colours.

**Comment by inVoltag** [comment]
Hello @MrFussyfont,
Thanks for reporting this issue.
Globally, some shades might be forced to be within the sRBG gamut (one the limit of the LCH color model), giving a lag between colors. Can I get your starting colors (and your lightness scale configuration) in order to test on my side?

**Comment by MrFussyfont** [comment]
Lightness is pretty close to 10 to 100 in steps of 10:
<img width="621" alt="image" src="https://user-images.githubusercontent.com/474540/225644255-01a91aaf-2343-4f9d-9d09-9a590d584d3e.png">

Starting colors: 064D58, 4D555B, 119029, 005A7A (and more, but these are enough to see the problem)

**Comment by inVoltag** [comment]
Thanks both for sharing your configuration with and your observation 👍 
I'm gonna investigate.

**Comment by MrFussyfont** [comment]
Using the same source color #2C7B84 in [Leonardo](https://leonardocolor.io/theme.html), and distributing lightness equally (using the "Distribute" dropdown after changing min/max lightness to 25/95), I get this:
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/474540/226365636-efe1d956-5888-4334-ba36-6aa426e957df.png">

In the "Use" tab I can output CSS in LCH format:
>   --Teal100: lch(95%, 3, 210deg);
>   --Teal200: lch(86%, 8, 207deg);
>   --Teal300: lch(78%, 12, 209deg);
>   --Teal400: lch(69%, 16, 208deg);
>   --Teal500: lch(60%, 20, 209deg);
>   --Teal600: lch(51%, 23, 209deg);
>   --Teal700: lch(42%, 22, 210deg);
>   --Teal800: lch(33%, 18, 211deg);
>   --Teal900: lch(25%, 15, 208deg);

So it's definitely adjusting chroma and hue. I guess this issue and the other one I posted about saturation are strongly related: if you can find a good formula to adjust chroma and hue, you can get a more consistent and pleasing palette?

**Comment by MrFussyfont** [comment]
Here's a clue: on the "Chromacity" tab, it gives you the model and formulas(?):

<img width="728" alt="image" src="https://user-images.githubusercontent.com/474540/226368723-db6b4e63-698f-4c6d-899b-d49fb2a62cb3.png">

**Comment by inVoltag** [comment]
Nice tips! It may help improve a lot the shades generation algorithm. I'm going open another issue to separate the algorithm from tweaking the chroma.

**Comment by inVoltag** [comment]
Hello @MrFussyfont,
I wanna show you a first audit about the palette generation (I have used your configuration). You can take a glance at this [report](https://docs.google.com/spreadsheets/d/16PcIhsIHgNmYL6tF-M0zS5u8ds4v7pXhRQrJFaXRizs/edit?usp=sharing). The next step is to improve the algorithm through its generation.

**Comment by MrFussyfont** [comment]
@inVoltag Thank you, but I'm not sure what I'm looking at in your report. Are these just the numbers from my colours using the existing algorithm? What are the "consolidation" graphs?

**Comment by MrFussyfont** [comment]
@inVoltag That's very interesting, thank you! The improved algorithm definitely produces more consistency in the lightness, though not as consistent as Leonardo. Comparing through a monochrome filter (Leonardo palette below yours):
<img width="597" alt="image" src="https://user-images.githubusercontent.com/474540/228635387-2d78e16f-41a7-4221-9e2b-ad9612913a7f.png">

I would need to spend a lot more time to really understand the complexity (so forgive me if I'm asking too much of a free plugin!), but I guess the ideal would be something like sliders to control the amount of lightness "correction" and/or the chroma and hue curves/adjustments. 

I don't know if I mentioned Primer Prism, but it takes this idea to an extreme where you can adjust the curves manually and then optionally apply them to all colors in the palette! See https://primer.style/prism/

**Comment by inVoltag** [comment]
Hi @MrFussyfont,
We are closer than before. There is still some improvements to bring more consistency. Nevertheless, I reached my limit in algorithm because I tried several formulas in vain. That's because the chroma curve must follow the sRGB gamut shape according to the hue value. So the complexity is proven and it needs more research to get closer to the following image:
![image](https://user-images.githubusercontent.com/10651214/230222495-0359cbe1-aed9-447d-b5e3-2aa526bedae9.png)

The current improvement is a first step and you may keep contributing to find together the golden formula.

**Comment by inVoltag** [comment]
Thanks for sharing Prism, it is a good inspiration for a next evolution to adjust the chroma.

**Comment by inVoltag** [comment]
The version 20 has been released. I suggest you to enable the algorithm in settings because this difference can be noticed (could be annoying for others users). You can test now then give me your feedback.

**Comment by MrFussyfont** [comment]
Thanks, looks good! I like having the option to switch the algorithm. Although the lightness is not as consistent as I would like, I'll mark this as resolved.
