### ISSUE TITLE
color organization bug

### ISSUE THREAD

**Issue by Hifilo** [inVoltag/figma-ui-color-palette#5]
Hello, was trying your plugin and noticed a bug when I made the palette. For whatever reason the plugin didn't organize the palette based on my layers, and it seemed to do its own thing. I tried changing numbers, but that didn't seem to have have an effect

Perhaps allowing us to reorganize the colors within the plugin may be an easy solution?

Thanks!

![UiColor palette](https://user-images.githubusercontent.com/92943726/196053905-8ff8bfcc-558a-48e1-b938-7a351e24faaa.png)

**Comment by inVoltag** [comment]
Hello @Hifilo,
The selection is not organize according to the elements tree (unfortunately). I can suggest you two solutions:
- As you said, allow to reorganize colors within the plugin (WIP)
- Sort colors alphabetically when creating a palette

**Comment by inVoltag** [comment]
Hello @Hifilo,
A new version of the plugin has been released. The version 9 allows you to reorder colors with drag and drop. Besides, the starting colors are sorted alphabetically (or from 0 to N) at creating a palette.
Feel free to reopen if the solution does not fit your need.
