### ISSUE TITLE
Documentation site not working

### ISSUE THREAD

**Issue by MrFussyfont** [inVoltag/figma-ui-color-palette#59]
I get a connection error when I try to load https://docs.ui-color-palette.com/
<img width="742" alt="image" src="https://user-images.githubusercontent.com/474540/233095335-b4c74236-dd36-435c-9b33-5193e9e1d507.png">

**Comment by inVoltag** [comment]
Hello @MrFussyfont,
I cannot reproduce on my side but I updated the short link to get to the release note (and the feedback form)
Could you try these urls:
- [https://docs.ui-color-palette.com](https://docs.ui-color-palette.com)
- [http://uicp.link/whats-new](http://uicp.link/whats-new)

I also suggest you to clear your cache.

**Comment by MrFussyfont** [comment]
@inVoltag Neither of those work for me (I'm in Canada, if that's helpful). I tried a private window and through a VPN:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/474540/233101260-6066d928-e18a-4f7a-a3b0-f241a978979a.png">

**Comment by inVoltag** [comment]
I may find the problem (the domain was unlinked with GitBook DNS). Could you retry to access both the urls?

**Comment by MrFussyfont** [comment]
Still not working for me. Tried a different browser too.

**Comment by inVoltag** [comment]
I renewed the SSL certificate, we might wait until 24 hours and then we'll check again.

**Comment by inVoltag** [comment]
Any new about the issue?

**Comment by MrFussyfont** [comment]
Sorry, yes, actually it worked one time last week, but today again it didn't. However, I think I found the problem -- it was a security setting on my Eero router. When I turn off "Advanced Security" then the documentation site loads.
