### ISSUE TITLE
Wrong lightness scale pre-selected when editing palette

### ISSUE THREAD

**Issue by MrFussyfont** [inVoltag/figma-ui-color-palette#60]
**Steps to reproduce**
1. Create a new palette and select IBM Carbon scale
2. Close the plugin
3. Select the palette frame and open the plugin to edit the palette

**Expected**
IBM Carbon scale is selected. Holding Shift while dragging the first or last stop distributes lightness equally.

**Actual**
Material scale is selected. Holding Shift while dragging the first stop creates additional stops, and while dragging the last only moves the last. 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/474540/233106875-287f3a75-368f-40a1-83b6-3d80787fc96c.png">

**Comment by inVoltag** [comment]
It should be fixed (my test are passed and ok). Would you be able to test this early version in dev? You can follow these [steps](https://github.com/inVoltag/figma-ui-color-palette#contribution) to install a plugin from your machine (choose the branch `fix-#60-wrong-lightness-preset`).

**Comment by inVoltag** [comment]
For your information, I deployed the version 21 that contains the fix 😄
